

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[2]
REPORTS_DIR = PROJECT_ROOT / "data" / "reports"

COMPANY_SIGNALS_PATH = REPORTS_DIR / "company_risk_signals.csv"
SECTOR_SIGNALS_PATH = REPORTS_DIR / "sector_risk_signals.csv"
TREND_SIGNALS_PATH = REPORTS_DIR / "risk_trend_signals.csv"


st.set_page_config(
    page_title="Portfolio Risk Signals",
    page_icon="📉",
    layout="wide",
)


@st.cache_data
def load_signal_data() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Load portfolio risk signal outputs generated by the batch pipeline."""
    required_paths = [COMPANY_SIGNALS_PATH, SECTOR_SIGNALS_PATH, TREND_SIGNALS_PATH]
    missing = [str(path) for path in required_paths if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing portfolio signal files. Run training/build_portfolio_signals.py first:\n"
            + "\n".join(missing)
        )

    company_df = pd.read_csv(COMPANY_SIGNALS_PATH)
    sector_df = pd.read_csv(SECTOR_SIGNALS_PATH)
    trend_df = pd.read_csv(TREND_SIGNALS_PATH)

    if "filing_date" in trend_df.columns:
        trend_df["filing_date"] = trend_df["filing_date"].fillna("unknown_date").astype(str)
        trend_df["filing_date_parsed"] = pd.to_datetime(
            trend_df["filing_date"], errors="coerce"
        )

    return company_df, sector_df, trend_df


st.title("Portfolio Risk Signals")
st.markdown(
    "This page converts paragraph- and filing-level model outputs into **portfolio-style risk signals**. "
    "The goal is to move from raw NLP predictions to company-, sector-, and time-series metrics that can be "
    "used for comparative risk monitoring."
)

st.markdown(
    "The signals shown here are derived from the filing summary outputs and emphasize **negative-risk density**, "
    "**high-confidence risk language**, and **changes in risk score over time**."
)

try:
    company_df, sector_df, trend_df = load_signal_data()
except Exception as exc:
    st.error(str(exc))
    st.stop()


st.sidebar.header("Filters")
available_sectors = sorted(company_df["sector"].dropna().astype(str).unique().tolist()) if not company_df.empty else []
available_tickers = sorted(company_df["ticker"].dropna().astype(str).unique().tolist()) if not company_df.empty else []

selected_sectors = st.sidebar.multiselect(
    "Sector",
    options=available_sectors,
    default=available_sectors,
)
selected_tickers = st.sidebar.multiselect(
    "Ticker",
    options=available_tickers,
    default=available_tickers,
)
min_company_risk = st.sidebar.slider(
    "Minimum company risk score",
    min_value=0.0,
    max_value=1.0,
    value=0.0,
    step=0.01,
)

filtered_company_df = company_df.copy()
if selected_sectors:
    filtered_company_df = filtered_company_df[
        filtered_company_df["sector"].isin(selected_sectors)
    ]
if selected_tickers:
    filtered_company_df = filtered_company_df[
        filtered_company_df["ticker"].isin(selected_tickers)
    ]
if "company_risk_score" in filtered_company_df.columns:
    filtered_company_df = filtered_company_df[
        filtered_company_df["company_risk_score"] >= min_company_risk
    ]

filtered_sector_df = sector_df.copy()
if selected_sectors:
    filtered_sector_df = filtered_sector_df[
        filtered_sector_df["sector"].isin(selected_sectors)
    ]

filtered_trend_df = trend_df.copy()
if selected_tickers:
    filtered_trend_df = filtered_trend_df[
        filtered_trend_df["ticker"].isin(selected_tickers)
    ]
if selected_sectors and not filtered_company_df.empty:
    valid_tickers = set(filtered_company_df["ticker"].tolist())
    filtered_trend_df = filtered_trend_df[
        filtered_trend_df["ticker"].isin(valid_tickers)
    ]


st.subheader("Overview")
col1, col2, col3, col4 = st.columns(4)
col1.metric("Companies", len(filtered_company_df))
col2.metric("Sectors", filtered_company_df["sector"].nunique() if not filtered_company_df.empty else 0)
col3.metric(
    "Avg Company Risk Score",
    f"{filtered_company_df['company_risk_score'].mean():.3f}" if not filtered_company_df.empty else "N/A",
)
col4.metric(
    "Avg Negative Risk Ratio",
    f"{filtered_company_df['avg_pct_negative_risk'].mean():.3f}" if not filtered_company_df.empty else "N/A",
)

st.markdown(
    "**Interpretation:** `company_risk_score` blends the share of paragraphs classified as `negative_risk` with the "
    "share of high-confidence risk paragraphs. Higher scores indicate filings whose disclosure language is more "
    "intensely risk-oriented."
)


st.subheader("Company Risk Leaderboard")
if filtered_company_df.empty:
    st.info("No companies match the current filters.")
else:
    company_display_cols = [
        "ticker",
        "company_name",
        "sector",
        "company_risk_score",
        "avg_pct_negative_risk",
        "avg_high_conf_risk_ratio",
        "filing_count",
        "avg_confidence",
    ]
    st.dataframe(
        filtered_company_df[company_display_cols].sort_values(
            ["company_risk_score", "avg_pct_negative_risk"],
            ascending=[False, False],
        ),
        use_container_width=True,
    )

    fig, ax = plt.subplots(figsize=(10, 4))
    rank_df = filtered_company_df.sort_values("company_risk_score", ascending=False)
    ax.bar(rank_df["ticker"], rank_df["company_risk_score"])
    ax.set_title("Company Risk Score")
    ax.set_xlabel("Ticker")
    ax.set_ylabel("Risk Score")
    plt.xticks(rotation=45)
    st.pyplot(fig)

st.markdown(
    "This leaderboard provides the most direct **portfolio-level signal** in the project. It can be used to rank "
    "companies by disclosure risk intensity and identify which names appear most exposed based on recent filings."
)


st.subheader("Sector Risk Comparison")
if filtered_sector_df.empty:
    st.info("No sector-level signals match the current filters.")
else:
    st.dataframe(filtered_sector_df, use_container_width=True)

    fig, ax = plt.subplots(figsize=(9, 4))
    sector_rank_df = filtered_sector_df.sort_values(
        "avg_company_risk_score", ascending=False
    )
    ax.bar(sector_rank_df["sector"], sector_rank_df["avg_company_risk_score"])
    ax.set_title("Average Company Risk Score by Sector")
    ax.set_xlabel("Sector")
    ax.set_ylabel("Average Company Risk Score")
    plt.xticks(rotation=30, ha="right")
    st.pyplot(fig)

st.markdown(
    "Sector aggregation helps identify whether risk language is concentrated in certain parts of the market. "
    "With a larger universe of companies, this becomes a useful lens for comparing sector-level stress."
)


st.subheader("Risk Change Over Time")
trend_changes = filtered_trend_df.dropna(subset=["risk_score_change"]).copy()
if trend_changes.empty:
    st.info(
        "No filing-over-filing risk changes are available yet. Add more dated filings per company to build trend signals."
    )
else:
    trend_display_cols = [
        "ticker",
        "company_name",
        "form_type",
        "filing_date",
        "risk_score",
        "previous_risk_score",
        "risk_score_change",
        "pct_negative_risk",
        "pct_negative_risk_change",
    ]
    st.dataframe(
        trend_changes[trend_display_cols].sort_values(
            ["risk_score_change"], ascending=[False]
        ),
        use_container_width=True,
    )

    if trend_changes["filing_date_parsed"].notna().any():
        st.markdown("**Per-company risk trajectories**")
        for ticker, group in trend_changes.groupby("ticker"):
            plot_group = group.sort_values("filing_date_parsed")
            if plot_group["filing_date_parsed"].notna().sum() < 2:
                continue

            fig, ax = plt.subplots(figsize=(8, 3))
            ax.plot(plot_group["filing_date_parsed"], plot_group["risk_score"], marker="o")
            ax.set_title(f"{ticker} Risk Score Over Time")
            ax.set_xlabel("Filing Date")
            ax.set_ylabel("Risk Score")
            st.pyplot(fig)

st.markdown(
    "`risk_score_change` captures whether disclosure language becomes more or less risk-intensive from one filing to the next. "
    "This is the most dynamic signal in the project and is especially relevant for monitoring changes over time."
)


st.subheader("How to use these signals")
st.markdown(
    "- **Company risk score** can be used as a ranking feature in a portfolio monitoring workflow.\n"
    "- **Sector risk score** can identify where disclosure stress is concentrated across the market.\n"
    "- **Risk change over time** can surface names whose filings have become materially more risk-heavy between periods."
)

st.caption(
    "Signals are generated by training/build_portfolio_signals.py using filing-level summaries produced by the SEC risk pipeline."
)