

import sys
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

REPORTS_DIR = PROJECT_ROOT / "data" / "reports"
REFERENCE_DIR = PROJECT_ROOT / "data" / "reference"

FILING_SUMMARY_PATH = REPORTS_DIR / "filing_prediction_summary.csv"
TICKER_METADATA_PATH = REFERENCE_DIR / "ticker_metadata.csv"

COMPANY_SIGNALS_PATH = REPORTS_DIR / "company_risk_signals.csv"
SECTOR_SIGNALS_PATH = REPORTS_DIR / "sector_risk_signals.csv"
TREND_SIGNALS_PATH = REPORTS_DIR / "risk_trend_signals.csv"


REQUIRED_FILING_COLUMNS = {
    "filing_id",
    "ticker",
    "company_name",
    "form_type",
    "filing_date",
    "total_paragraphs",
    "negative_risk",
    "neutral",
    "positive_outlook",
    "high_conf_risk_count",
    "pct_negative_risk",
    "avg_confidence",
}


def load_filing_summary() -> pd.DataFrame:
    """Load the filing-level prediction summary generated by the pipeline."""
    if not FILING_SUMMARY_PATH.exists():
        raise FileNotFoundError(
            "Missing filing summary report. Run training.summarize_predictions first: "
            f"{FILING_SUMMARY_PATH}"
        )

    df = pd.read_csv(FILING_SUMMARY_PATH)
    missing = REQUIRED_FILING_COLUMNS - set(df.columns)
    if missing:
        raise ValueError(f"Filing summary is missing required columns: {sorted(missing)}")

    df = df.copy()
    df["filing_date"] = df["filing_date"].fillna("unknown_date").astype(str)
    return df


def load_ticker_metadata() -> pd.DataFrame:
    """Load optional ticker-to-sector metadata for sector-level aggregation."""
    if not TICKER_METADATA_PATH.exists():
        print(
            "[WARN] No ticker metadata file found. Sector-level signals will use an 'Unknown' sector."
        )
        return pd.DataFrame(columns=["ticker", "company_name", "sector"])

    try:
        metadata = pd.read_csv(TICKER_METADATA_PATH)
    except pd.errors.EmptyDataError:
        print(
            "[WARN] Ticker metadata file exists but is empty. Sector-level signals will use an 'Unknown' sector."
        )
        return pd.DataFrame(columns=["ticker", "company_name", "sector"])

    required_cols = {"ticker", "sector"}
    missing = required_cols - set(metadata.columns)
    if missing:
        raise ValueError(
            f"Ticker metadata is missing required columns: {sorted(missing)}"
        )

    if metadata.empty:
        print(
            "[WARN] Ticker metadata file has headers but no rows. Sector-level signals will use an 'Unknown' sector."
        )
        return pd.DataFrame(columns=["ticker", "company_name", "sector"])

    metadata = metadata.copy()
    metadata["ticker"] = metadata["ticker"].astype(str).str.strip().str.upper()
    metadata["sector"] = metadata["sector"].fillna("Unknown").astype(str).str.strip()

    if "company_name" not in metadata.columns:
        metadata["company_name"] = None

    return metadata[["ticker", "company_name", "sector"]].drop_duplicates(subset=["ticker"])


def add_derived_filing_metrics(df: pd.DataFrame) -> pd.DataFrame:
    """Create filing-level ratios used to build portfolio risk signals."""
    enriched = df.copy()
    enriched["ticker"] = enriched["ticker"].astype(str).str.strip().str.upper()
    enriched["high_conf_risk_ratio"] = (
        enriched["high_conf_risk_count"] / enriched["total_paragraphs"]
    ).round(4)
    enriched["risk_score"] = (
        0.7 * enriched["pct_negative_risk"] + 0.3 * enriched["high_conf_risk_ratio"]
    ).round(4)
    return enriched


def build_company_signals(
    filing_df: pd.DataFrame,
    metadata_df: pd.DataFrame,
) -> pd.DataFrame:
    """Aggregate filing-level metrics into company-level portfolio risk signals."""
    company_df = (
        filing_df.groupby(["ticker", "company_name"], dropna=False)
        .agg(
            filing_count=("filing_id", "count"),
            total_paragraphs=("total_paragraphs", "sum"),
            total_negative_risk=("negative_risk", "sum"),
            total_high_conf_risk=("high_conf_risk_count", "sum"),
            avg_pct_negative_risk=("pct_negative_risk", "mean"),
            avg_high_conf_risk_ratio=("high_conf_risk_ratio", "mean"),
            company_risk_score=("risk_score", "mean"),
            avg_confidence=("avg_confidence", "mean"),
        )
        .reset_index()
    )

    company_df = company_df.round(
        {
            "avg_pct_negative_risk": 4,
            "avg_high_conf_risk_ratio": 4,
            "company_risk_score": 4,
            "avg_confidence": 4,
        }
    )

    if metadata_df.empty:
        company_df["sector"] = "Unknown"
    else:
        company_df = company_df.merge(
            metadata_df[["ticker", "sector"]],
            on="ticker",
            how="left",
        )
        company_df["sector"] = company_df["sector"].fillna("Unknown")

    company_df = company_df.sort_values(
        ["company_risk_score", "avg_pct_negative_risk"],
        ascending=[False, False],
    ).reset_index(drop=True)
    return company_df


def build_sector_signals(company_df: pd.DataFrame) -> pd.DataFrame:
    """Aggregate company-level signals into sector-level risk signals."""
    sector_df = (
        company_df.groupby("sector", dropna=False)
        .agg(
            company_count=("ticker", "count"),
            filing_count=("filing_count", "sum"),
            total_paragraphs=("total_paragraphs", "sum"),
            avg_company_risk_score=("company_risk_score", "mean"),
            avg_pct_negative_risk=("avg_pct_negative_risk", "mean"),
            avg_high_conf_risk_ratio=("avg_high_conf_risk_ratio", "mean"),
            avg_confidence=("avg_confidence", "mean"),
        )
        .reset_index()
        .round(4)
    )

    sector_df = sector_df.sort_values(
        ["avg_company_risk_score", "avg_pct_negative_risk"],
        ascending=[False, False],
    ).reset_index(drop=True)
    return sector_df


def build_risk_trend_signals(filing_df: pd.DataFrame) -> pd.DataFrame:
    """Compute filing-over-filing changes in risk score for each company."""
    trend_df = filing_df.copy()

    trend_df["filing_date_parsed"] = pd.to_datetime(
        trend_df["filing_date"],
        errors="coerce",
    )

    trend_df = trend_df.sort_values(
        ["ticker", "filing_date_parsed", "filing_id"],
        ascending=[True, True, True],
    ).reset_index(drop=True)

    trend_df["previous_risk_score"] = trend_df.groupby("ticker")["risk_score"].shift(1)
    trend_df["risk_score_change"] = (
        trend_df["risk_score"] - trend_df["previous_risk_score"]
    ).round(4)
    trend_df["previous_pct_negative_risk"] = trend_df.groupby("ticker")["pct_negative_risk"].shift(1)
    trend_df["pct_negative_risk_change"] = (
        trend_df["pct_negative_risk"] - trend_df["previous_pct_negative_risk"]
    ).round(4)

    ordered_cols = [
        "filing_id",
        "ticker",
        "company_name",
        "form_type",
        "filing_date",
        "total_paragraphs",
        "pct_negative_risk",
        "high_conf_risk_ratio",
        "risk_score",
        "previous_risk_score",
        "risk_score_change",
        "previous_pct_negative_risk",
        "pct_negative_risk_change",
        "avg_confidence",
    ]

    return trend_df[ordered_cols]


def print_console_summary(
    company_df: pd.DataFrame,
    sector_df: pd.DataFrame,
    trend_df: pd.DataFrame,
) -> None:
    """Print a concise overview of the generated portfolio signals."""
    print(f"[INFO] Company signals generated: {len(company_df)}")
    print(f"[INFO] Sector signals generated: {len(sector_df)}")
    print(f"[INFO] Trend rows generated: {len(trend_df)}")

    if not company_df.empty:
        print("\n[INFO] Top company risk signals:")
        print(
            company_df[
                [
                    "ticker",
                    "company_name",
                    "sector",
                    "company_risk_score",
                    "avg_pct_negative_risk",
                    "avg_high_conf_risk_ratio",
                    "filing_count",
                ]
            ].head(10).to_string(index=False)
        )

    if not sector_df.empty:
        print("\n[INFO] Sector-level risk signals:")
        print(sector_df.to_string(index=False))

    trend_changes = trend_df.dropna(subset=["risk_score_change"])
    if not trend_changes.empty:
        print("\n[INFO] Largest positive risk score changes:")
        print(
            trend_changes.sort_values("risk_score_change", ascending=False)[
                [
                    "ticker",
                    "filing_date",
                    "risk_score",
                    "previous_risk_score",
                    "risk_score_change",
                ]
            ].head(10).to_string(index=False)
        )



def main() -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)

    filing_df = load_filing_summary()
    metadata_df = load_ticker_metadata()
    filing_df = add_derived_filing_metrics(filing_df)

    company_df = build_company_signals(filing_df, metadata_df)
    sector_df = build_sector_signals(company_df)
    trend_df = build_risk_trend_signals(filing_df)

    company_df.to_csv(COMPANY_SIGNALS_PATH, index=False)
    sector_df.to_csv(SECTOR_SIGNALS_PATH, index=False)
    trend_df.to_csv(TREND_SIGNALS_PATH, index=False)

    print_console_summary(company_df, sector_df, trend_df)

    print(f"\n[INFO] Wrote company signals to {COMPANY_SIGNALS_PATH}")
    print(f"[INFO] Wrote sector signals to {SECTOR_SIGNALS_PATH}")
    print(f"[INFO] Wrote trend signals to {TREND_SIGNALS_PATH}")


if __name__ == "__main__":
    main()